export { Hero } from "./Hero";
export { FeaturedProducts } from "./FeaturedProducts";
export { Categories } from "./Categories";
export { WhyChooseUs } from "./WhyChooseUs";
export { Testimonials } from "./Testimonials";
export { CTABanner } from "./CTABanner";
export { Stats } from "./Stats";
export { HowItWorks } from "./HowItWorks";
export { FAQ } from "./FAQ";
